from __future__ import annotations

import json
import re

from langchain_core.documents import Document
from langchain_openai import ChatOpenAI
from pydantic import BaseModel, Field

from app.config import Settings, get_settings
from app.models.schemas import (
    DirectAskResponse,
    DiseasePrediction,
    MedicineInfo,
    PredictResponse,
    RetrievalPipeline,
    SourceCitation,
)
from app.rag.retriever import hybrid_retrieve

DISCLAIMER = (
    "This tool is for educational purposes only and is not a medical diagnosis. "
    "It does not replace professional medical advice, diagnosis, or treatment. "
    "Always consult a qualified healthcare provider for personal medical decisions."
)

DIRECT_DISCLAIMER = (
    "This answer was generated by the language model without searching your uploaded "
    "PDFs or Kaggle datasets (no RAG). It may be incomplete or incorrect. "
    "It is not medical advice."
)

ROUTER_PROMPT = """Classify the user message.
Return JSON only:
{"is_health": true or false, "reason": "short reason"}

is_health=true only if the user is describing symptoms, a health complaint, a disease,
medicines, or asking for a possible medical condition.
is_health=false for sports, coding, trivia, news, homework, chit-chat, and anything
not about personal/clinical health.
"""

SYSTEM_PROMPT = """You are a careful clinical knowledge assistant for an educational symptom tracker.
Use ONLY the provided context from medical PDFs and datasets to suggest possible conditions and medicines.
Never invent drug dosages. Prefer general medicine names mentioned in context.
If context does not support an answer, return empty diseases.
Respond with valid JSON only, matching this schema:
{
  "diseases": [
    {
      "name": "string",
      "likelihood": "high|moderate|low",
      "rationale": "string grounded in context",
      "medicines": [{"name": "string", "notes": "optional string"}]
    }
  ],
  "summary": "short overall note"
}
"""

DIRECT_SYSTEM_PROMPT = """You are a general helpful assistant.
The user chose to skip the medical knowledge base (no RAG).
Answer clearly and briefly. If the topic is medical, remind them this is not a diagnosis.
Do not claim you searched their uploaded books.
"""


class LLMMedicine(BaseModel):
    name: str
    notes: str | None = None


class LLMDisease(BaseModel):
    name: str
    likelihood: str = "low"
    rationale: str = ""
    medicines: list[LLMMedicine] = Field(default_factory=list)


class LLMPayload(BaseModel):
    diseases: list[LLMDisease] = Field(default_factory=list)
    summary: str = ""


class RouterPayload(BaseModel):
    is_health: bool = False
    reason: str = ""


def _format_context(docs: list[Document]) -> str:
    if not docs:
        return "No retrieved context available."
    blocks = []
    for i, doc in enumerate(docs, start=1):
        meta = doc.metadata or {}
        title = meta.get("source", "unknown")
        src_type = meta.get("type", "unknown")
        page = meta.get("page")
        header = f"[{i}] source={title} type={src_type}"
        if page is not None:
            header += f" page={page}"
        blocks.append(f"{header}\n{doc.page_content}")
    return "\n\n".join(blocks)


def _docs_to_citations(docs: list[Document]) -> list[SourceCitation]:
    citations: list[SourceCitation] = []
    for doc in docs:
        meta = doc.metadata or {}
        title = str(meta.get("source", "unknown"))
        page = meta.get("page")
        if page is not None:
            title = f"{title} (p.{page})"
        snippet = doc.page_content.strip()
        if len(snippet) > 280:
            snippet = snippet[:277] + "..."
        citations.append(
            SourceCitation(
                title=title,
                snippet=snippet,
                source_type=str(meta.get("type", "unknown")),
                vector_distance=_opt_float(meta.get("vector_distance")),
                bm25_score=_opt_float(meta.get("bm25_score")),
                rrf_score=_opt_float(meta.get("rrf_score")),
                rerank_score=_opt_float(meta.get("rerank_score")),
                match_confidence=_opt_float(meta.get("match_confidence")),
            )
        )
    return citations


def _opt_float(value: object) -> float | None:
    if value is None or value == "":
        return None
    try:
        return round(float(value), 4)
    except (TypeError, ValueError):
        return None


def _extract_json(text: str) -> dict:
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", text, re.DOTALL)
        if match:
            return json.loads(match.group(0))
        raise


def _llm(settings: Settings) -> ChatOpenAI:
    return ChatOpenAI(
        model=settings.openai_chat_model,
        api_key=settings.openai_api_key,
        temperature=0.2,
    )


def _classify_is_health(text: str, llm: ChatOpenAI) -> RouterPayload:
    message = llm.invoke(
        [
            {"role": "system", "content": ROUTER_PROMPT},
            {"role": "user", "content": text.strip()},
        ]
    )
    content = message.content if isinstance(message.content, str) else str(message.content)
    try:
        return RouterPayload.model_validate(_extract_json(content))
    except Exception:
        return RouterPayload(is_health=True, reason="Classifier fallback: treat as health query.")


def _trace_to_pipeline(trace) -> RetrievalPipeline:
    return RetrievalPipeline(
        vector_asked=trace.vector_asked,
        vector_kept=trace.vector_kept,
        bm25_asked=trace.bm25_asked,
        bm25_kept=trace.bm25_kept,
        rrf_merged=trace.rrf_merged,
        rerank_input=trace.rerank_input,
        final_kept=trace.final_kept,
        reranker_used=trace.reranker_used,
    )


def _out_of_scope(
    reason: str,
    docs: list[Document] | None = None,
    pipeline: RetrievalPipeline | None = None,
) -> PredictResponse:
    return PredictResponse(
        diseases=[],
        sources=_docs_to_citations(docs or []),
        disclaimer=DISCLAIMER,
        raw_answer=reason,
        used_rag=False,
        out_of_scope=True,
        allow_direct_llm=True,
        scope_reason=reason,
        pipeline=pipeline,
    )


def predict_from_symptoms(symptoms: str, settings: Settings | None = None) -> PredictResponse:
    settings = settings or get_settings()
    if not settings.openai_configured:
        return PredictResponse(
            diseases=[],
            sources=[],
            disclaimer=DISCLAIMER,
            raw_answer="OPENAI_API_KEY is not configured.",
            used_rag=False,
            out_of_scope=True,
            allow_direct_llm=False,
            scope_reason="OpenAI is not configured.",
        )

    llm = _llm(settings)
    route = _classify_is_health(symptoms, llm)
    if not route.is_health:
        return _out_of_scope(
            "This question is outside the medical knowledge base (RAG). "
            "The symptom tracker will not invent an answer from unrelated PDF chunks. "
            "You can ask the language model directly instead."
        )

    hits, trace = hybrid_retrieve(symptoms, settings)
    pipeline = _trace_to_pipeline(trace)
    docs = [hit.doc for hit in hits]
    if not docs:
        return _out_of_scope(
            "No sufficiently similar passages were found in your uploaded PDFs or Kaggle data. "
            "RAG will not guess. You can ask the language model directly (without RAG).",
            pipeline=pipeline,
        )

    context = _format_context(docs)
    user_prompt = (
        f"Patient symptoms:\n{symptoms.strip()}\n\n"
        f"Retrieved medical context:\n{context}\n\n"
        "Return JSON only."
    )
    message = llm.invoke(
        [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ]
    )
    content = message.content if isinstance(message.content, str) else str(message.content)

    try:
        payload = LLMPayload.model_validate(_extract_json(content))
    except Exception:
        return PredictResponse(
            diseases=[],
            sources=_docs_to_citations(docs),
            disclaimer=DISCLAIMER,
            raw_answer=content,
            used_rag=True,
            pipeline=pipeline,
        )

    diseases = [
        DiseasePrediction(
            name=d.name,
            likelihood=d.likelihood,
            rationale=d.rationale,
            medicines=[MedicineInfo(name=m.name, notes=m.notes) for m in d.medicines],
        )
        for d in payload.diseases
    ]

    return PredictResponse(
        diseases=diseases,
        sources=_docs_to_citations(docs),
        disclaimer=DISCLAIMER,
        raw_answer=payload.summary or None,
        used_rag=True,
        out_of_scope=False,
        allow_direct_llm=False,
        pipeline=pipeline,
    )


def ask_llm_direct(question: str, settings: Settings | None = None) -> DirectAskResponse:
    settings = settings or get_settings()
    llm = _llm(settings)
    message = llm.invoke(
        [
            {"role": "system", "content": DIRECT_SYSTEM_PROMPT},
            {"role": "user", "content": question.strip()},
        ]
    )
    content = message.content if isinstance(message.content, str) else str(message.content)
    return DirectAskResponse(answer=content, disclaimer=DIRECT_DISCLAIMER, used_rag=False)
